title: StopStore
description: "The best tech deals and news."
encoding: "utf-8"
markdown: kramdown
baseurl: "/stopstore-simple"
url: "https://him001133.github.io"
permalink: /:year/:month/:day/:title/

# Categories and Tags
category_archive_path: "/categories/"
tag_archive_path: "/tags/"
